fix: feedback and back to top button mobile spacing
carbon-design-system/gatsby-theme-carbon pull request #1052
Opened 2020-11-03 20:33 UTC by alisonjoseph

Closes #1024

Updates spacing on mobile only for feedback and back to top button

2020-11-06 15:19 UTC, sstrubberg approved these changes

2020-11-06 18:20 UTC, aagonzales approved these changes

2020-11-09 21:42 UTC, vpicone requested changes

2020-11-09 21:42 UTC, vpicone commented on packages/gatsby-theme-carbon/src/components/FeedbackDialog/LaunchButton.module.scss
> +    bottom: calc(6rem + 8px);
```suggestion
    bottom: 6.5rem;
```

2020-11-09 21:42 UTC, vpicone commented on packages/gatsby-theme-carbon/src/components/FeedbackDialog/LaunchButton.module.scss
> +    bottom: calc(6rem + 8px);
Unless I'm missing something 🔍

2020-11-10 20:01 UTC, alisonjoseph commented
Updated @vpicone not sure where the `+8px` came from originally but see no reason to keep it,

2020-11-10 20:07 UTC, vpicone approved these changes
🚀 she’s back, folks 🚀

2020-11-10 20:09 UTC, alisonjoseph commented
What's with the lint commit message error? is that from using GitHub to merge in that fix? 💀

2020-11-17 15:54 UTC, merged

2020-12-11 21:30 UTC, mjabbink commented
This needs to be applied to IDL please.