[DO NOT MERGE] V11 migration
carbon-design-system/gatsby-theme-carbon pull request #1209
Opened 2022-01-19 21:18 UTC by aledavila

v11 migration start

2022-02-25 21:37 UTC, jnm2377 approved these changes

2022-02-28 15:28 UTC, sstrubberg requested changes
Holy cow.. this is incredible work. Thank you @aledavila and @jnm2377 for doing this. Two things came to mind as I was reviewing this.
1) The Header needs a little touch up.
![header](https://user-images.githubusercontent.com/15822070/156009870-ddb42066-1c2b-4ae3-b7d8-f37ac0fb37c8.gif)
2) Have you all updated the Example site to complement this upgrades?

2022-02-28 16:08 UTC, joshblack commented on packages/example/src/pages/guides/styling.mdx
>  Every Sass file in your project automatically has access to the the following
Were you able to "auto-import" styles with Sass modules to mirror how the theme currently works?

2022-02-28 16:09 UTC, joshblack commented on packages/gatsby-theme-carbon/src/components/ArticleCard/article-card.scss
> +// $carbon--white-0
```suggestion
```

Small clean-up nit, the comments are great while developing but may be better off excluded from the final code.

2022-03-02 18:52 UTC, aledavila commented on packages/example/src/pages/components/Aside.mdx
> +Mozilla Developer Network’s documentation for more information. Props for accessibility labels are described in the
So the v11 inline notifications don't allow for links inside of them anymore for accessibility issues. I'm not sure what we should do in this case.

2022-03-02 21:07 UTC, tay1orjones commented on packages/example/src/pages/components/Aside.mdx
> +Mozilla Developer Network’s documentation for more information. Props for accessibility labels are described in the
`ActionableNotification` can be used, it accepts an `inline` prop.

2022-03-02 21:21 UTC, tay1orjones reviewed
This looks great! The deploy preview doesn't seem to have any problems. Below is just a few items I'm curious about.

2022-03-02 21:21 UTC, tay1orjones commented on packages/example/src/pages/components/InlineNotification.mdx
> +information to a user. For accessibility reasons, `<InlineNotification>` content cannot include interactive elements, just text.
`ActionableNotification` accepts an `inline` prop that can be used here. It should mostly be a drop-in replacement from a usage perspective.

2022-03-02 21:21 UTC, tay1orjones commented on packages/gatsby-theme-carbon/src/styles/index.scss
> +// @include react.type-classes();
Do we need something here? The type looks fine on the preview site to me.

2022-03-02 21:21 UTC, tay1orjones commented on packages/gatsby-theme-carbon/src/styles/internal/_carbon-components.scss
> +// @use '@carbon/react/scss/components/ui-shell/ui-shell';
Did we need to have these in, or are the per-component styles brought in okay through the main entrypoint?

2022-03-02 21:21 UTC, tay1orjones commented on packages/gatsby-theme-carbon/src/styles/internal/resources.scss
> +// @use '@carbon/react/scss/utilities/convert' as *;
This should be available now if we want to continue using it.

2022-03-03 20:33 UTC, tay1orjones approved these changes

2022-03-03 20:34 UTC, merged