feat: new config option to add default mdx layouts
carbon-design-system/gatsby-theme-carbon pull request #1214
Opened 2022-01-26 20:05 UTC by xlegs

Adds a new configuration option that allows user to additional `gatsby-plugin-mdx` layouts.

#### Changelog

**New**

- A new extraLayouts option is added to the theme's `gatsby-config.js`. It defaults to an empty object.

#### Usage

In a project using `gatsby-theme-carbon`, the user can add their own `gatsby-plugin-mdx` layout like so:

```
  {
      resolve: 'gatsby-theme-carbon',
      options: {
        navigationStyle: 'header',
        mediumAccount: 'carbondesign',
        isSwitcherEnabled: false,
        titleType: 'prepend',
        extraLayouts: {
          posts: require.resolve('./src/layouts/postLayout.js')
        },
...
```

where `posts` is defined in the same file with `gatsby-source-filesystem`.

2022-01-26 20:10 UTC, sstrubberg requested changes
Super cool. Would you be open to adding some guidance around this feature in the example site to accompany the changes?

2022-01-31 15:06 UTC, sstrubberg approved these changes

2022-02-02 16:47 UTC, aledavila approved these changes
thanks for the contribution :)

2022-02-16 00:26 UTC, xlegs commented
Is this on track for a merge?

2022-02-16 06:32 UTC, merged