Fix: code blocks in mdx + issues/868
carbon-design-system/gatsby-theme-carbon pull request #1422
Opened 2024-02-20 20:19 UTC by muditjuneja

This PR fixes the following - 

- Show more button in Code blocks
- Added a prop to enable/disable Show more button in Code blocls
- Added text wrap to avoid horizontal scroll

Should close - https://github.com/carbon-design-system/gatsby-theme-carbon/issues/868

2024-02-20 20:21 UTC, muditjuneja commented on packages/gatsby-theme-carbon/src/components/Code/Code.js
> +  hideCode = false,
With this, by default, we are not doing the "Show more" in code blocks.

2024-02-21 15:14 UTC, eng618 requested changes
The changes look really good, the only thing I would like to see is the examples updated to reflect this change. Especially adding an example for the **Show More** prop. This would be in the **packages/example/src/pages/components/code-blocks.mdx** file.

2024-03-02 21:56 UTC, muditjuneja commented on packages/gatsby-theme-carbon/gatsby-config.mjs
> +import rehypeAddCodeMetaData from 'rehype-mdx-fenced-code-meta-support';
Created a rehype package which is adding a new prop of named metaData which is being passed in Code.js.

Here is the dirty package - https://www.npmjs.com/package/rehype-mdx-fenced-code-meta-support

2024-03-03 00:26 UTC, eng618 commented
Lets add some padding to the show more button so it doesn’t overlap the content.

<img width="303" alt="image" src="https://github.com/carbon-design-system/gatsby-theme-carbon/assets/3827863/c33fd90b-d742-4407-af71-b3e68fe3ba2a">

2024-03-03 00:33 UTC, eng618 approved these changes
Approving now, but would be good to add the padding to the show more button before we merge this in.

2024-03-03 07:58 UTC, muditjuneja commented
> Lets add some padding to the show more button so it doesn’t overlap the content.
> 
> <img alt="image" width="303" src="https://private-user-images.githubusercontent.com/3827863/309510924-c33fd90b-d742-4407-af71-b3e68fe3ba2a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk0NTI5NzAsIm5iZiI6MTcwOTQ1MjY3MCwicGF0aCI6Ii8zODI3ODYzLzMwOTUxMDkyNC1jMzNmZDkwYi1kNzQyLTQ0MDctYWY3MS1iM2U2OGZlM2JhMmEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDNUMDc1NzUwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDM5ZjIzZTVlZWY3ZTE0ZjkxNjUzMWFlZjUyYjFkMDBiOWRiMDZkYmVkNTZiN2Q1MTA3NmQxZTAxYjc5N2U1MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Q0S0QzhCIATkJYHHnIgT575RO-WvJUBJIzklN9GnMTo">

I will do that in another follow up PR. Merging this one now.

2024-03-03 07:59 UTC, muditjuneja commented
> > Lets add some padding to the show more button so it doesn’t overlap the content.
> > <img alt="image" width="303" src="https://private-user-images.githubusercontent.com/3827863/309510924-c33fd90b-d742-4407-af71-b3e68fe3ba2a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk0NTI5NzAsIm5iZiI6MTcwOTQ1MjY3MCwicGF0aCI6Ii8zODI3ODYzLzMwOTUxMDkyNC1jMzNmZDkwYi1kNzQyLTQ0MDctYWY3MS1iM2U2OGZlM2JhMmEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDNUMDc1NzUwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDM5ZjIzZTVlZWY3ZTE0ZjkxNjUzMWFlZjUyYjFkMDBiOWRiMDZkYmVkNTZiN2Q1MTA3NmQxZTAxYjc5N2U1MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Q0S0QzhCIATkJYHHnIgT575RO-WvJUBJIzklN9GnMTo">
> 
> I will do that in another follow up PR. Merging this one now.

I guess I can't merge. I will make that small change.

2024-03-03 08:35 UTC, merged