fix: ordered list alignment in safari
carbon-design-system/gatsby-theme-carbon pull request #991
Opened 2020-09-10 20:44 UTC by jnm2377

Closes #985 
 
- adds webkit-padding for safari only
- **testing**: view in Safari browser, compare localhost/preview to existing list example on live site and see alignment has changed: https://gatsby-theme-carbon.now.sh/components/markdown#lists

2020-09-10 20:50 UTC, vpicone approved these changes
Awesome, adding the issue numbers can be helpful I think, especially now that VS Code let's you open them from the editor

2020-09-10 20:50 UTC, vpicone commented on packages/gatsby-theme-carbon/src/components/markdown/Markdown.module.scss
> +  -webkit-padding-start: 0.5ch; // needed to align ordered lists to body copy in Safari
```suggestion
  -webkit-padding-start: 0.5ch; // needed to align ordered lists to body copy in Safari #985
```

2020-09-10 20:57 UTC, vpicone requested changes
![IMG_F58B955E6D95-1](https://user-images.githubusercontent.com/4078018/92804838-3cd14d00-f37e-11ea-973c-eeec2e6c5291.jpeg)

It looks like the nested list items could use this as well, maybe update the rule at line 75 to be:

```
:global(.bx--list--ordered) {
  list-style: decimal;
  -webkit-padding-start: 0.5ch; // needed to align ordered lists to body copy in Safari #985
}
```

Not sure why the `, ol` was there but looks like it can be removed.

2020-09-11 20:39 UTC, jnm2377 commented
@vpicone looks like the nested list alignment was off on chrome too, so I updated it for both. I also changed the way I was targeting the safari only fixes bc for some reason it was affecting chrome too. Should be good now.

2020-09-11 21:39 UTC, vpicone commented on packages/gatsby-theme-carbon/src/components/markdown/Markdown.module.scss
> +:global(.bx--list--ordered.bx--list--nested) {
@jnm2377 Do you mind maybe moving the comment up hear and making it a little more descriptive? I think this markdown style sheet is getting buck wild and I won't remember what happened in a month haha.

2020-09-14 20:08 UTC, vpicone approved these changes

2020-09-15 01:35 UTC, merged